
name: CI

permissions:
  contents: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DBT_CLOUD: ${{secrets.DBT_CLOUD}}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build
  
  env-dev:
    runs-on: ubuntu-latest
    # environment: dev
    steps:
      - uses: actions/checkout@v3
        # name: code pull
        # working-directory: snowflake-clone/test
        # run: |
      - name: Install dbt
        run: |
          wget https://github.com/dbt-labs/dbt-cli/releases/download/v0.38.15/dbt_0.38.15_linux_amd64.tar.gz
          tar -xf dbt_0.38.15_linux_amd64.tar.gz
          ls -la
          mkdir -p ~/.dbt
          echo $DBT_CLOUD > ~/.dbt/dbt_cloud.yml
          cat ~/.dbt/dbt_cloud.yml
          export PATH="/usr/local/bin:$PATH" >> ~/.bashrc
          ./dbt --version
      - name: Run dbt
        run: |
          ls -la
          dbt run 
