
name: CI

permissions:
  contents: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: '*'
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DBT_CLOUD: ${{vars.DBT_CLOUD}}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build
  
  env-dev:
    runs-on: ubuntu-latest
    # environment: dev
    steps:
      - uses: actions/checkout@v3
        # name: code pull
        # working-directory: snowflake-clone/test
        # run: |
      - name: Install dbt
        run: |
          wget https://github.com/dbt-labs/dbt-cli/releases/download/v0.38.15/dbt_0.38.15_linux_amd64.tar.gz
          tar -xf dbt_0.38.15_linux_amd64.tar.gz
          ls -la
          mkdir -p ~/.dbt
          cp dbt_cloud.yml  ~/.dbt/
          echo =========================
          cat ~/.dbt/dbt_cloud.yml
          echo =========================
          export PATH="$PWD/dbt:$PATH" >> ~/.bashrc
          source ~/.bashrc
          pip install 'shandy-sqlfmt[jinjafmt]'
          ./dbt --version
      - name: format check
        run: |
          sqlfmt --check .
      - name: Run dbt
        run: |
          ls -la
          ./dbt run 
      - name: Generate documentation
        run: |
          ./dbt docs generate
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dist-without-markdown
      #     path: |
      #       target/
      - name: hosting documentation 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/
